---
name : General Question
description : I have a general question about cheat sheets.
title: "<cheat sheet name>: <brief description of issue/question>"
---

body:
- type: markdown
  attributes:
    value: "If you're looking to submit a new cheat sheet or a translation, read the [contributing guidelines](https://github.com/rstudio/cheatsheets/blob/master/.github/CONTRIBUTING.md) and submit a pull request."
- type: textarea
  attributes:
  value: |
    "<!-- 
    Hello! 
    
    In the title of this issue please include one of the following
    a. the cheat sheet name, and language if it's a translation
    b. the phrase "general question", if not about a specific cheat sheet
    c. the phrase "website" and then a brief description of your issue
    Ex. Data Transformation - c_across missing or Website - last updated dates inaccurate
    
    If you're looking to contribute a cheat sheet you made, an updated to a cheat sheet you previously submitted, 
    or a new/updated translation, please read the contributing guidelines and submit a pull request.
    
    Some common questions
    Q1. I would like to translate a cheat sheet but do not see the original Keynote/Powerpoint/etc file.
    A1. All cheat sheets created by RStudio should include either a Keynote or PowerPoint file, usually both. 
    Some of the user submitted cheat sheets however may not. In that case [TODO]
    --> "
- type: markdown
  attributes:
    value: "Cheat sheet development happens in bursts so your issue may sit for a while. Thank you for taking the time to ask questions/provide feedback/etc"
