---
name : General Question
description : I have a general question about cheat sheets.
title: "<cheat sheet name>: <brief description of issue/question>"
---

body:
- type: markdown
  attributes:
    value: "If you're looking to submit a new cheat sheet or a translation, read the [contributing guidelines](https://github.com/rstudio/cheatsheets/blob/master/.github/CONTRIBUTING.md) and submit a pull request."
